name: Report Card

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: creekorful/goreportcard-action@v1.0
    - name: Go report card
   
